// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyknhykaxdkrgtyttndw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5a25oeWtheGRrcmd0eXR0bmR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzODY4NTksImV4cCI6MjA2MDk2Mjg1OX0.tAF5qAlfUNwkJ2P34C24_WdFh91_apyvr3Lwzr66g4g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);